[mysql]
host = "127.0.0.1"
port = 3306
database = "douyin"
username = "root"
password = "821342"
charset = "utf8mb4"
parse_time = true
loc = "Local"

[redis]
host = "127.0.0.1"
port = 6379
database = 0

[server]
ip = "127.0.0.1"
port = 8080

[path]
ffmpeg_path = "D:\\Go_WorkSpace\\src\\byte_douyin\\lib\\ffmpeg.exe"
static_source_path = "D:\\Go_WorkSpace\\src\\byte_douyin\\static"
